version: '3.8'

services:
  chess-server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: chess-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
